<?php
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * @file
 * A description of what your module does.
 */

function arms_theme($existing, $type, $theme, $path) {
  return [
    'arms_expeditions_detail' => [
      'variables' => [
        'expedition' => NULL,
      ],
    ],
    'arms_deployment_detail' => [
      'variables' => [
        'deployment' => NULL,
        'deploymentId' => NULL,
        'projectId' => NULL,
      ],
    ],
  ];
}
