<?php
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * @file
 * A description of what your module does.
 */

function arms_theme($existing, $type, $theme, $path) {
  return [
    'arms_expeditions_detail' => [
      'variables' => [
        'expedition' => NULL,
      ],
    ],
    'arms_deployment_detail' => [
      'variables' => [
        'deployment' => NULL,
        'expedition' => NULL,
      ],
    ],
    'arms_query_results' => [
      'variables' => [
        'deployments' => NULL,
      ],
    ],
    'block--carouselblock' => [
      'variables' => [
        'imgs' => NULL,
        'width' => NULL,
        'height' => NULL,
        'id' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_page_attachments().
 */
function arms_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'arms/redirect-command';
}
