Drop if table exists `armsExpeditions`;
CREATE TABLE `armsExpeditions` (
	  `expeditionId` int(11) unsigned NOT NULL,
	  `principalInvestigator` varchar(125) NOT NULL DEFAULT '',
	  `contactName` varchar(125) NOT NULL DEFAULT '',
	  `fundingSource` varchar(1000) NOT NULL DEFAULT '',
	  `envisionedDuration` int(4) NOT NULL,
	  `geographicScope` varchar(1000) NOT NULL DEFAULT '',
	  `goals` text NOT NULL,
	  `leadOrganization` varchar(255) NOT NULL DEFAULT '',
	  `contactEmail` varchar(255) NOT NULL DEFAULT '',
	  PRIMARY KEY (`expeditionId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

Drop if table exists `deployments`;
CREATE TABLE `deployments` (
	  `deploymentId` varchar(255),
	  `actualDeploymentDate` datetime,
	  `actualDeploymentTimeOfDay` datetime DEFAULT NULL,
	  `actualRecoveryDate` datetime,
	  `actualRecoveryTimeOfDay` datetime DEFAULT NULL,
	  `armsModel` varchar(255),
	  `attachmentMethod` varchar(255) DEFAULT NULL,
	  `continentOcean` varchar(18) DEFAULT '',
	  `country` varchar(50) DEFAULT '',
	  `county` varchar(50) DEFAULT NULL,
	  `dataEntryPersonInCharge` varchar(125) DEFAULT NULL,
	  `deploymentPersonInCharge` varchar(125) DEFAULT NULL,
	  `depthInMeters` int(6),
	  `depthOfBottomMeters` int(6) DEFAULT NULL,
	  `durationToProcessing` int(3) DEFAULT NULL,
	  `errorRadius` int(4) DEFAULT NULL,
	  `habitat` varchar(255) DEFAULT NULL,
	  `horizontalDatum` varchar(40) DEFAULT NULL,
	  `intendedDeploymentDate` datetime,
	  `intendedRecoveryDate` datetime,
	  `intendedSoakTimeInYears` int(3),
	  `island` varchar(100) DEFAULT NULL,
	  `islandGroup` varchar(100) DEFAULT NULL,
	  `decimalLatitude` float,
	  `locality` varchar(100) DEFAULT NULL,
	  `decimalLongitude` float,
	  `newOrReused` varchar(6) DEFAULT '',
	  `notes` text,
	  `numLayers` int(3),
	  `numReplicatesInSet` int(5) DEFAULT NULL,
	  `photoUrl` varchar(2083) DEFAULT '',
	  `processingPersonInCharge` varchar(125) DEFAULT NULL,
	  `recoveryPersonInCharge` varchar(125) DEFAULT NULL,
	  `region` varchar(100) DEFAULT NULL,
	  `removalProtocol` varchar(255) DEFAULT NULL,
	  `stateProvince` varchar(100) DEFAULT NULL,
	  `stationId` varchar(255),
	  `hasScrubbieLayer` varchar(3) DEFAULT '',
	  `substrateType` varchar(4) DEFAULT NULL,
	  `id` int(11) unsigned AUTO_INCREMENT,
	  `expeditionId` int(11) unsigned,
	  `laminates` varchar(3) DEFAULT '',
	  `weightsAttached` varchar(3) DEFAULT '',
	  `intentToBarcode` varchar(9) DEFAULT '',
	  `intentToCollectOtherDatatypes` varchar(9) DEFAULT '',
	  `intentToMetabarcode` varchar(9) DEFAULT '',
	  `intentToPhotographPlates` varchar(9) DEFAULT '',
	  `intentToPhotographSpecimens` varchar(9) DEFAULT '',
	  `siteDetail` text,
    `replicateLabel` varchar(10) DEFAULT NULL,
	  PRIMARY KEY (`id`),
	  KEY `FKk94yxos6l5qr88ur2eqxq1e2m` (`expeditionId`),
    KEY `deployments_deploymentId_inx` (`deploymentId`),
	  CONSTRAINT `FKk94yxos6l5qr88ur2eqxq1e2m` FOREIGN KEY (`expeditionId`) REFERENCES `armsExpeditions` (`expeditionId`),
	  CONSTRAINT `deployments_ibfk_1` FOREIGN KEY (`expeditionId`) REFERENCES `armsExpeditions` (`expeditionId`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;
